---
#creating network client server
- name: Delete network
  docker_network:
    name: "{{ network_name }}"
    state: absent
    force: yes
    
- name: Delete server
  docker_container:
    name: "{{ server_name }}"
    state: absent

- name: Delete client
  docker_container:
    name: "{{ client_name }}"
    state: absent    
    
- name: Create network for application
  docker_network:
    name: "{{ network_name }}"
    ipam_config:
      - subnet: "{{ subnet }}"
          
- name: Creating container with server
  docker_container:
    name: "{{ server_name }}"
    image: python:{{ python_ver }}-alpine
    command: python server.py
    volumes:
      - "{{ script_path }}:/usr/src/myapp"
    working_dir: /usr/src/myapp
    networks_cli_compatible: yes
    networks:
      - name: "{{ network_name }}"
        ipv4_address: "{{ server_ip }}"
    state: started

- name: Creating container with client
  docker_container:
    name: "{{ client_name }}"
    image: python:{{ python_ver }}-alpine
    command: python client.py
    volumes:
      - "{{ script_path }}:/usr/src/myapp"
    working_dir: /usr/src/myapp
    networks_cli_compatible: yes
    networks:
      - name: "{{ network_name }}"
        ipv4_address: "{{ client_ip }}"
    state: started
